import { CHARACTER_BY_ID } from '../../sim/characters';
import type { CombatVfxEvent, CombatVfxEventType, CombatVfxPresetMap } from './types';

export const COMBAT_VFX_PRESET_LIBRARY: CombatVfxPresetMap = {
  boost_core: {
    particles: {
      color: '#7bc2ff',
      lifetimeSeconds: 0.2,
      startScale: 1.1,
      endScale: 3.2,
      startOpacity: 0.72,
      endOpacity: 0.05,
      driftAlongDirection: 10,
      driftVertical: 0.5,
    },
    trail: {
      color: '#5dafff',
      width: 0.5,
      length: 5.6,
      lifetimeSeconds: 0.16,
      startOpacity: 0.52,
      endOpacity: 0.03,
    },
    flash: {
      color: '#8fd2ff',
      radius: 1.8,
      thickness: 0.13,
      lifetimeSeconds: 0.16,
      startScale: 0.95,
      endScale: 1.9,
      startOpacity: 0.6,
      endOpacity: 0.06,
    },
    sound: {
      waveform: 'sawtooth',
      frequencyHz: 260,
      durationSeconds: 0.09,
      gain: 0.018,
    },
  },
  launch_strike: {
    particles: {
      color: '#ffd06b',
      lifetimeSeconds: 0.28,
      startScale: 1.8,
      endScale: 4.2,
      startOpacity: 0.8,
      endOpacity: 0.08,
      driftAlongDirection: 4.2,
      driftVertical: 1.2,
    },
    trail: {
      color: '#ffc86a',
      width: 0.42,
      length: 4.6,
      lifetimeSeconds: 0.2,
      startOpacity: 0.55,
      endOpacity: 0.08,
    },
    flash: {
      color: '#ffce7a',
      radius: 2.7,
      thickness: 0.2,
      lifetimeSeconds: 0.22,
      startScale: 1,
      endScale: 2.15,
      startOpacity: 0.86,
      endOpacity: 0.07,
    },
    sound: {
      waveform: 'triangle',
      frequencyHz: 380,
      durationSeconds: 0.12,
      gain: 0.026,
    },
  },
  launch_arcane: {
    particles: {
      color: '#b4a0ff',
      lifetimeSeconds: 0.32,
      startScale: 2,
      endScale: 4.8,
      startOpacity: 0.84,
      endOpacity: 0.1,
      driftAlongDirection: 3.2,
      driftVertical: 1.4,
    },
    trail: {
      color: '#9b87ff',
      width: 0.48,
      length: 5,
      lifetimeSeconds: 0.24,
      startOpacity: 0.58,
      endOpacity: 0.09,
    },
    flash: {
      color: '#c3afff',
      radius: 3,
      thickness: 0.18,
      lifetimeSeconds: 0.25,
      startScale: 1,
      endScale: 2.3,
      startOpacity: 0.86,
      endOpacity: 0.08,
    },
    sound: {
      waveform: 'square',
      frequencyHz: 340,
      durationSeconds: 0.13,
      gain: 0.024,
    },
  },
  clash_burst: {
    particles: {
      color: '#f4d7ff',
      lifetimeSeconds: 0.34,
      startScale: 2.6,
      endScale: 6.2,
      startOpacity: 0.92,
      endOpacity: 0.08,
      driftAlongDirection: 6.4,
      driftVertical: 1.8,
    },
    trail: {
      color: '#b6a3ff',
      width: 0.62,
      length: 6.8,
      lifetimeSeconds: 0.24,
      startOpacity: 0.62,
      endOpacity: 0.08,
    },
    flash: {
      color: '#fff2ff',
      radius: 4.2,
      thickness: 0.28,
      lifetimeSeconds: 0.28,
      startScale: 0.95,
      endScale: 2.7,
      startOpacity: 0.94,
      endOpacity: 0.06,
    },
    sound: {
      waveform: 'triangle',
      frequencyHz: 470,
      durationSeconds: 0.14,
      gain: 0.03,
    },
  },
  super_boost_core: {
    particles: {
      color: '#6d8cff',
      lifetimeSeconds: 0.3,
      startScale: 1.8,
      endScale: 5.2,
      startOpacity: 0.86,
      endOpacity: 0.06,
      driftAlongDirection: 16,
      driftVertical: 1,
    },
    trail: {
      color: '#6d8cff',
      width: 0.82,
      length: 9.5,
      lifetimeSeconds: 0.24,
      startOpacity: 0.76,
      endOpacity: 0.04,
    },
    flash: {
      color: '#9aaaff',
      radius: 2.7,
      thickness: 0.22,
      lifetimeSeconds: 0.24,
      startScale: 0.9,
      endScale: 2.5,
      startOpacity: 0.82,
      endOpacity: 0.05,
    },
    sound: {
      waveform: 'sawtooth',
      frequencyHz: 190,
      durationSeconds: 0.14,
      gain: 0.026,
    },
  },
  parry_guard: {
    particles: {
      color: '#b7fff5',
      lifetimeSeconds: 0.24,
      startScale: 1.4,
      endScale: 3.7,
      startOpacity: 0.72,
      endOpacity: 0.06,
      driftAlongDirection: 0,
      driftVertical: 0.9,
    },
    trail: {
      color: '#a6fff2',
      width: 0.35,
      length: 3.2,
      lifetimeSeconds: 0.16,
      startOpacity: 0.46,
      endOpacity: 0.04,
    },
    flash: {
      color: '#cbfff7',
      radius: 2.35,
      thickness: 0.16,
      lifetimeSeconds: 0.2,
      startScale: 1,
      endScale: 2,
      startOpacity: 0.8,
      endOpacity: 0.05,
    },
    sound: {
      waveform: 'triangle',
      frequencyHz: 530,
      durationSeconds: 0.1,
      gain: 0.02,
    },
  },
  special_cast: {
    particles: {
      color: '#ffe58c',
      lifetimeSeconds: 0.3,
      startScale: 1.7,
      endScale: 4.4,
      startOpacity: 0.84,
      endOpacity: 0.05,
      driftAlongDirection: 5.4,
      driftVertical: 1.2,
    },
    trail: {
      color: '#ffd46a',
      width: 0.5,
      length: 5.8,
      lifetimeSeconds: 0.24,
      startOpacity: 0.62,
      endOpacity: 0.04,
    },
    flash: {
      color: '#fff1b5',
      radius: 3.1,
      thickness: 0.2,
      lifetimeSeconds: 0.28,
      startScale: 0.9,
      endScale: 2.2,
      startOpacity: 0.9,
      endOpacity: 0.05,
    },
    sound: {
      waveform: 'triangle',
      frequencyHz: 410,
      durationSeconds: 0.13,
      gain: 0.026,
    },
  },
  special_vanguard_bastion: {
    particles: {
      color: '#83ffe2',
      lifetimeSeconds: 0.46,
      startScale: 3.4,
      endScale: 5.9,
      startOpacity: 0.48,
      endOpacity: 0.03,
      driftAlongDirection: 0,
      driftVertical: 0.45,
    },
    flash: {
      color: '#cafff3',
      radius: 4.6,
      thickness: 0.38,
      lifetimeSeconds: 0.46,
      startScale: 0.74,
      endScale: 1.32,
      startOpacity: 0.94,
      endOpacity: 0.08,
    },
    sound: {
      waveform: 'sine',
      frequencyHz: 190,
      durationSeconds: 0.2,
      gain: 0.03,
    },
  },
  special_duelist_pressure_dash: {
    particles: {
      color: '#ff70bc',
      lifetimeSeconds: 0.3,
      startScale: 1.1,
      endScale: 3.2,
      startOpacity: 0.88,
      endOpacity: 0.04,
      driftAlongDirection: 17,
      driftVertical: 0.65,
    },
    trail: {
      color: '#ff4da8',
      width: 0.82,
      length: 12.5,
      lifetimeSeconds: 0.34,
      startOpacity: 0.86,
      endOpacity: 0.03,
    },
    flash: {
      color: '#ffd0e9',
      radius: 2.25,
      thickness: 0.17,
      lifetimeSeconds: 0.25,
      startScale: 0.82,
      endScale: 2.05,
      startOpacity: 0.9,
      endOpacity: 0.04,
    },
    sound: {
      waveform: 'sawtooth',
      frequencyHz: 520,
      durationSeconds: 0.11,
      gain: 0.026,
    },
  },
  break_burst: {
    particles: {
      color: '#ffb15f',
      lifetimeSeconds: 0.28,
      startScale: 2.1,
      endScale: 4.8,
      startOpacity: 0.86,
      endOpacity: 0.06,
      driftAlongDirection: 5.2,
      driftVertical: 1.1,
    },
    trail: {
      color: '#ff9451',
      width: 0.56,
      length: 5.4,
      lifetimeSeconds: 0.18,
      startOpacity: 0.58,
      endOpacity: 0.04,
    },
    flash: {
      color: '#ffd6a3',
      radius: 3.1,
      thickness: 0.22,
      lifetimeSeconds: 0.22,
      startScale: 1,
      endScale: 2.1,
      startOpacity: 0.86,
      endOpacity: 0.05,
    },
    sound: {
      waveform: 'square',
      frequencyHz: 300,
      durationSeconds: 0.11,
      gain: 0.026,
    },
  },
  projectile_cast: {
    particles: {
      color: '#7ad1ff',
      lifetimeSeconds: 0.2,
      startScale: 1.1,
      endScale: 2.6,
      startOpacity: 0.66,
      endOpacity: 0.05,
      driftAlongDirection: 2,
      driftVertical: 0.5,
    },
    trail: {
      color: '#6ebdfd',
      width: 0.3,
      length: 4.4,
      lifetimeSeconds: 0.26,
      startOpacity: 0.5,
      endOpacity: 0.06,
    },
    flash: {
      color: '#a5e0ff',
      radius: 1.6,
      thickness: 0.12,
      lifetimeSeconds: 0.16,
      startScale: 1,
      endScale: 1.7,
      startOpacity: 0.58,
      endOpacity: 0.04,
    },
    sound: {
      waveform: 'sine',
      frequencyHz: 450,
      durationSeconds: 0.09,
      gain: 0.018,
    },
  },
  dunk_impact: {
    particles: {
      color: '#8cffbf',
      lifetimeSeconds: 0.28,
      startScale: 2,
      endScale: 4.5,
      startOpacity: 0.85,
      endOpacity: 0.08,
      driftAlongDirection: 2.2,
      driftVertical: 1.3,
    },
    trail: {
      color: '#81f8b7',
      width: 0.44,
      length: 4.9,
      lifetimeSeconds: 0.2,
      startOpacity: 0.56,
      endOpacity: 0.07,
    },
    flash: {
      color: '#b5ffd2',
      radius: 2.85,
      thickness: 0.2,
      lifetimeSeconds: 0.24,
      startScale: 1,
      endScale: 2.2,
      startOpacity: 0.84,
      endOpacity: 0.08,
    },
    sound: {
      waveform: 'triangle',
      frequencyHz: 240,
      durationSeconds: 0.12,
      gain: 0.028,
    },
  },
};

export const COMBAT_VFX_EVENT_BINDINGS: Record<CombatVfxEventType, string> = {
  boost: 'boost_core',
  super_boost: 'super_boost_core',
  launch: 'launch_strike',
  clash: 'clash_burst',
  parry: 'parry_guard',
  special: 'special_cast',
  break: 'break_burst',
  projectile: 'projectile_cast',
  dunk: 'dunk_impact',
};

export const CHARACTER_VFX_EVENT_OVERRIDES: Record<string, Partial<Record<CombatVfxEventType, string>>> = {
  character_vanguard_vfx: {
    special: 'special_vanguard_bastion',
  },
  character_duelist_vfx: {
    special: 'special_duelist_pressure_dash',
  },
  character_ace_vfx: {
    launch: 'launch_arcane',
  },
};

export function hasCharacterVfxProfile(profileId: string): boolean {
  return Boolean(CHARACTER_VFX_EVENT_OVERRIDES[profileId]);
}

export function resolveCombatVfxPresetId(event: CombatVfxEvent): string {
  const profileId = CHARACTER_BY_ID[event.characterId]?.visuals.vfxProfileId;
  const profileOverride = profileId ? CHARACTER_VFX_EVENT_OVERRIDES[profileId]?.[event.type] : undefined;
  return profileOverride ?? COMBAT_VFX_EVENT_BINDINGS[event.type];
}

export function resolveCombatVfxPreset(event: CombatVfxEvent) {
  const presetId = resolveCombatVfxPresetId(event);
  return COMBAT_VFX_PRESET_LIBRARY[presetId] ?? COMBAT_VFX_PRESET_LIBRARY[COMBAT_VFX_EVENT_BINDINGS[event.type]];
}

